export default {
  employees: [
    {id: 1, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 2, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 3, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},
    {id: 4, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 5, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 6, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},{id: 1, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 2, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 3, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},
    {id: 4, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 5, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 6, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},{id: 1, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 2, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 3, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},
    {id: 4, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 5, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 6, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},{id: 1, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 2, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 3, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},
    {id: 4, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 5, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 6, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},{id: 1, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 2, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 3, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},
    {id: 4, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 5, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 6, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},{id: 1, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 2, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 3, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},
    {id: 4, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 5, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 6, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},{id: 1, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 2, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 3, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},
    {id: 4, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 5, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 6, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},{id: 1, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 2, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 3, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},
    {id: 4, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 5, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 6, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},{id: 1, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 2, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 3, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},
    {id: 4, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 5, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 6, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},{id: 1, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 2, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 3, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},
    {id: 4, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 5, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 6, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},{id: 1, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 2, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 3, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},
    {id: 4, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 5, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 6, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},{id: 1, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 2, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 3, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},
    {id: 4, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 5, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 6, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},{id: 1, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 2, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 3, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},
    {id: 4, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 5, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 6, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},{id: 1, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 2, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 3, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},
    {id: 4, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 5, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 6, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},{id: 1, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 2, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 3, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},
    {id: 4, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 5, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 6, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},{id: 1, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 2, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 3, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},
    {id: 4, name: 'Руслан', surname: 'Шхалиев', patronymic: 'Мушвиг оглы', position: 'Директор'},
    {id: 5, name: 'Антон', surname: 'Богданов', patronymic: 'Васильевич', position: 'Монтажер'},
    {id: 6, name: 'Собака', surname: 'Сутулая', patronymic: 'Облезлович', position: 'Пес'},
  ],
}